server:
  port: ${PORT:3001}

spring:
  dataSource:
    url: ${URL_DB:jdbc:postgresql://movieland-pg:5432/movieland}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: debug

movie:
  random:
    countOfMovies: 3