server:
  port: ${PORT:3001}

spring:
  profiles:
    active: jpa
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/movieland}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: info

movie:
  random-count: 3

cache:
  update:
    interval-hours: 4
  delay: 4

currency:
  nbu-exchange-url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json

---
spring:
  config:
    activate:
      on-profile: jooq
  jooq:
    sql-dialect: POSTGRES

---
spring:
  config:
    activate:
      on-profile: jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
