server:
  port: ${PORT:3001}

spring:
  profiles:
    active:
#      - completable-future-enrichment
      - parallel-enrichment
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/movieland}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
#      hibernate.generate_statistics: true
#      hibernate.format_sql: true

logging:
  level:
    root: info


movie:
  random-count: 3

cache:
  update:
    interval-hours: 4
  delay: 4

currency:
  nbu-exchange-url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?

jwt:
  secret-key: YTJkM2Y0ZjViNjc4OTBhYmNkZWYxMjM0NTY3ODkwYWJjZGVm
  expiration: 3600000 # 1 hour in milliseconds

enrich:
  timeout: 5 # seconds

