  name: CI/CD

  on:
    workflow_dispatch:
    push:
        branches: [ master ]

  env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    SERVER_IP: ${{ secrets.SERVER_IP }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  jobs:
      docker:
          runs-on: ubuntu-latest

          steps:
              - name: Checkout code
                uses: actions/checkout@v4

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

              - name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
#                    username: rynkvaj
#                    password: o1d2e3s4a5

              - name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: rynkvaj/movieland:latest
      deploy:
        runs-on: ubuntu-latest
        needs: docker

        steps:
          - name: Deploy via SSH and run docker-compose
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.SERVER_IP }}
              username: ${{ secrets.SERVER_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                docker-compose down
                docker-compose pull
                docker-compose up -d
