name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  URL_DB: ${{ secrets.URL_DB }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: sudo chmod +x gradlew

      - name: Build JAR
        run: ./gradlew clean test bootJar

  dockerise:
   runs-on: ubuntu-latest
   needs: build

   steps:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

     - name: Show files
       run: ls -la

     - name: Fix Dockerfile permissions
       run: chmod 644 Dockerfile

     - name: Build and push Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/movieland:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerise

    steps:
      - name: Deploy via SSH and run docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker-compose down
            docker-compose pull
            docker-compose up -d
